### ISSUE TITLE
collectd vs golang-based default monitors?

### ISSUE THREAD

**Issue by jalaziz** [signalfx/signalfx-agent#1000]
First, I apologize if this is not the best place to ask this.

It seems that there are a set of go-based monitors that were added earlier this year that duplicate all the metrics offered by the default set of collectd monitors. These include:

- cpu
- filesystems
- memory
- disk-io
- net-io
- vmem

It appears that in at least some cases, the go-based monitors have more fidelity. For example, the `filesystems` monitor included dimensions for both the device and mountpoint, while the `df` collectd plugin will only tag by one of them.

It also appears that the go-based monitors were primarily added for Windows support.

Is there a general recommendation on which to use? If the recommendation is to use the collect plugins, should we just replace colllectd plugins with their go-based equivalents when we want the extra dimensions?

**Comment by keitwb** [comment]
@jalaziz yes, the Go-based monitors were primarily written for Windows support, since we can't easily run collectd on Windows.  My recommendation would be to always use the Go-based monitors and avoid the `collectd/*` ones.  We'll remove the warning about them being beta on Linux soon.  Collectd has a very limited metric metadata capability, and, in addition to the limited dimensionality as you mentioned, the dimensions that are present have vague names like `plugin_instance`, instead of something more descriptive like `device`.

If you find anything in a `collectd/*` monitor that isn't in the Go-based ones, let us know because the plan is to get rid the `collectd/*` monitors for host-based metrics altogether.  We just haven't tested them on Linux very much to be confident enough to make them default, but there are no known issues with them either.  They use a very well tested library under the covers (https://github.com/shirou/gopsutil).

Actually, just this past week we found that the `collectd/df` plugin does not work properly when running the agent on the Kubernetes containerd runtime, but the `filesystems` monitor does work.  So that, along with your comment here, will hopefully provide some impetus for getting the new Go-based monitors made default.

We are planning an upcoming 5.0 major release of the agent and that seems like the logical release to do the switch.  Of course, you can use them with current agent releases no problem though.  Let us know if you find any issues.

**Comment by jalaziz** [comment]
Thanks for the info! We'll start switching to the go-based monitors and will report if anything doesn't work or is missing.

**Comment by jalaziz** [comment]
Also, the dimensionality issue is certainly confusing. We ran into issues with a few other monitors (like the JMX one), until we realized what was going on.

As a side note, is the plan to migrate most monitors to go? Will there continue to be a python bridge?

**Comment by keitwb** [comment]
Yes, we intend on eventually replacing almost all of the `collectd/*` monitors with an equivalent non-collectd based one (usually Go-based), and some day hopefully stop bundling collectd altogether.  The most recent example of this is the `collectd/genericjmx` monitor being superseded by the `jmx` monitor, which is technically not Go-based since you have to use Java to access JMX, but the key thing is that it uses native SignalFx datapoints instead of collectd value lists so you can get much clearer dimensions.

The Python bridge for collectd (used by all `collectd/*` Python based plugins, and by `collectd/python` monitor) we will probably keep indefinitely because it doesn't actually use the collectd runtime at all, just a shim that implements the Python interface.  However, the same thing applies that we intend on offering an equivalent non-collectd monitor.  Some are already done like `elasticsearch` and `haproxy`.

**Comment by jalaziz** [comment]
Makes sense. I asked about the python bridge because, at least in our case, it would broaden the pool of people that would contribute/update integrations. Good to know that it will stick around in some form.

What about the telegraf agent? Will that remain?  I ask because it would be nice to be able to use standard open-source integrations. Prometheus and telegraf _seem_ to be the current OSS standards. We would consider using the telegraf agent ourselves, but the discovery rules of the SignalFx agent are too nice to abandon.

**Comment by jalaziz** [comment]
> I believe the current intent with Telegraf is to contribute a SignalFx output plugin to it and allow people to use the upstream Telegraf instead of us having to maintain [a fork of it](https://github.com/signalfx/telegraf) that is constantly out of date. There is [an open PR to do this](https://github.com/influxdata/telegraf/pull/5204) (contributed by a user), but has been stuck for a while -- I'll check if the blocking issue has been resolved yet.

Oh great, didn't see that!

> I think the biggest difference in using the Telegraf agent (other than getting access to a lot more integrations) is that you will be less able to use the built-in content and infrastructure views in the product, but since most users end up building their own custom dashboard content anyway, this probably isn't a big deal. Also, Telegraf (as far as I know) doesn't have the concept of properties on dimensions like we do (and that our agent makes use of in certain places), but again this is probably not a big deal if your monitoring requirements aren't too complex.

I actually only recently learned about properties on dimensions, but don't see a use case for them. As for the instructure views, it looks like the fork has a set of plugins to transform metrics such that the built-in dashboards and infrastructure view work? Are there no plans to move those plugins over too? I guess it wouldn't solve the problem of the other built-in dashboards, though.

In any case, we plan to use k8s anyway, so will probably stick to the SignalFx agent. Given that it doesn't look like discovery is coming to Telegraf anytime soon, it would be cool to see more support for telegraf plugins in the agent. To be fair, I've spent no time in trying to understand the technical complexity of such an integration, so feel free to ignore me.

**Comment by keitwb** [comment]
My understanding is that the Telegraf plugin we have in our fork to massage the metrics to conform to our expected structure was not acceptable in the mainline version of Telegraf since it offered no general value to the core user base of Telegraf.  I think it wasn't possible to do everything with the generic filter system in Telegraf either.  It would probably be easier for us to just make the infrastructure view work with vanilla Telegraf than try and change Telegraf.

We do have some embedded Telegraf plugins in the agent (all that start with `telegraf/`).  A lot of those were done to get some quick Windows support, but they should work on Linux fine too.  They are pretty easy to add -- it's basically just a config passthrough and some boilerplate to bridge the metric output.  We are open to adding strategic ones to our agent, but in general our preference is to make our existing monitors better and to write our own to have more flexibility on making changes/enhancements.

**Comment by jalaziz** [comment]
Makes sense.

Saw the telegraf plugins that were already embedded, but also noticed that there wasn't a generic one like with collectd. Not sure if it makes sense to try and make a generic one, but that's a different issue for a different day.

Really appreciate all this! Been very helpful in helping us understand where and how we could contribute.
