### ISSUE TITLE
Issues with docker observer and host-based networking

### ISSUE THREAD

**Issue by jalaziz** [signalfx/signalfx-agent#1004]
Somewhat related to #907.

While setting up the agent in our environment, we came across a series of issues with the docker observer and the way the agent handles endpoints, especially when using host networking. While we managed to work around the issues, it certainly seems like the agent could be improved to reduce friction. The issues were:

1. When using host networking and `useHostnameIfPresent: true`, the `host` config  parameter ends up being the machine's hostname. However, in some cases, we actually want to use `localhost`. In our case, this is true for `consul`. `consul` only binds to localhost to avoid exposing the API for security reasons. We were able to work around this by using the `host` observer, but with that, we lose the extra metadata provided through the `docker` observer. Our current config is:
```
- type: collectd/consul
  discoveryRule: discovered_by == "host" && port == 8500
```

2. The observer requires ports to be exposed (this can be done via a Dockerfile or at runtime). This in itself is not a major issue, but starts to breakdown when using `--net=host` as you don't need to expose ports anymore. The observer will still work with host networking as long as the ports were exposed in the Dockerfile.

3. For some containers, the ports exposed via the Dockerfile aren't the ones you want to check against. This is particularly true for the JMX check (as well as Kafka and Cassandra). For example, the default confluent image for Kafka does not expose the JMX port. The monitor configuration would fail to find the Kafka container if the discovery rule searches for the JMX port. The other option is to use the Kafka "listening" port 9092. This makes Kafka observable, but the port is wrong.

4. You cannot override the "discovered" port by supplying your own `port` config. The discovered port overwrites the supplied `port`. This is true for `host` as well. Luckily, for JMX checks, we can supply a custom serviceUrl which takes precedence above all this, allowing us to override the port that way.
Our Kafka monitor config looks like this for example:
```
- type: collectd/kafka
  # Override url temporarily until we more widely deploy a new kafka image that exposes JMX ports
  serviceURL: service:jmx:rmi:///jndi/rmi://{{.Host}}:9999/jmxrmi
  clusterName: ${ENV_NAME}-${REGION}
  discoveryRule: container_name == "kafka" && port == 9092
```

Allowing users to override the discovered host and port would solve most, if not all, the issues we faced. It would be great if we could supply the host or port manually to overwrite what is discovered by observers in special cases (especially with host networking).

**Comment by keitwb** [comment]
For the "unexposed" port issues, PR #907 will help with 2, 3, and 4, but I need to figure out how to do it in a backwards compatible way cleanly -- that is why it has been sitting for a while.  It is actually the next story I'm working on so you should see some progress on that soon.  It will allow you to specify a `port` config option on a monitor that also has a discovery rule.

For 1, there is a hacky workaround:

```yaml
 - type: jmx                                   
   configEndpointMappings:
     host: '"127.0.0.1"'  # Nested quotes are necessary since value is parsed as expression
   discoveryRule: container_image =~ "cassandra" && port == 7199
   groovyScript: {"#from": "/etc/signalfx/cassandra.groovy", raw: true}
```

I had cassandra running with `--net host` and had the same issue with hostname resolving to non-localhost.

This is kind of an abuse of `configEndpointMappings` since you aren't actually using any of the values from the endpoint itself, but it works as a means of essentially overriding the value coming from the endpoint emitted by the observer.

Actually, the hack with `configEndpointMappings` will work for your points 2,3, and 4 as well (just use `port` instead of `host`, you can even specify both).  The main thing #907 will do is make the discovery rule clearer and allow overriding `port` (and `host` by the time it is done) directly, which is more intuitive.  It will also allow matching containers that don't have any ports exposed since in that case the observer would emit nothing.

Additionally, see the docs on [Configuration from Labels](https://github.com/signalfx/signalfx-agent/blob/master/docs/observers/docker.md#configuration-from-labels) for the `docker` observer that might be useful to you.  Any ports you specify in the label config will be emitted from the `docker` observer as if they were exposed in the Dockerfile.

**Comment by jalaziz** [comment]
Thanks for the `configEndpointMappings` hadn't thought of that. Gave up after overriding `host` and `port` failed. In the JMX case, overriding `serviceURL` works, but glad there's a more universal workaround.

As for labels, I was looking at that and intend to start migrating to using labels, but it will likely happen when we start deploying k8s more widely.

Closing in favor of #907 since it should cover everything mentions here.
