### ISSUE TITLE
Fatal error with optional consul remote config source

### ISSUE THREAD

**Issue by jalaziz** [signalfx/signalfx-agent#1005]
Our config includes:
```
  - {"#from": "consul:signalfx/monitors/*", flatten: true, optional: true}
```

This may be intentional, but if the consul service is not available, the smart agent dies after logging the following error: 
```
time="2019-10-01T06:40:39Z" level=error msg="Error loading main config" configPath="/etc/signalfx/agent.yaml" error="could not resolve path consul:signalfx/monitors/*: Get http://localhost:8500/v1/kv/signalfx/monitors?recurse=: dial tcp [::1]:8500: connect: connection refused"
````

Since the path is optional, should the appropriate behavior be to log the failure and continue?

**Comment by keitwb** [comment]
It is more intentional than not -- `optional` means that the key might not match anything in Consul, and that a lack of matching should not result in an error, but rather just resolve to nothing.  It was not intended to mean that the Consul service itself was optional.

For the sake of backwards compatibility, I think the clearest thing to do would be to add an option to the `configSources` section that allows it to tolerate service outages (e.g. `allowMissing: true` or something).  If any `#from` reference were not optional, then it would still fail, but optional ones would work.

Another question is, if you did have monitor config in `signalfx/monitors/*` in Consul and the agent started up when Consul was down, what would you expect to happen?  Would you expect the agent to 1) pick up the config at some point automatically after Consul became available (essentially requiring the agent poll Consul periodically) or 2) never get the config unless it was manually restarted?  2 is fairly simple to implement since it requires nothing extra beyond the proposed additional flag above, but 1 is significantly more complex.

**Comment by jalaziz** [comment]
> Another question is, if you did have monitor config in `signalfx/monitors/*` in Consul and the agent started up when Consul was down, what would you expect to happen? Would you expect the agent to 1) pick up the config at some point automatically after Consul became available (essentially requiring the agent poll Consul periodically) or 2) never get the config unless it was manually restarted?

I was thinking about that and it's a tough one. In our particular case, the latter would work fine. We currently use systemd (and hopefully moving to k8s sooner rather than later) and the container will restart if it fails a few times. So the case of Consul not being available temporarily (especially at first boot) is not a major issue.

However, for the sake of robustness, option 1 is probably the best behavior. I was hoping option 1 would be relatively simply given there's already some polling logic, but now that I think about, you're probably using the native watch APIs for the different sources (to be fair, haven't look at the code around this).

Would it make sense to get option 2 out and then keep a ticket open for option 1?

**Comment by keitwb** [comment]
The point about system startup is a good one -- I was thinking about Consul as a service running on other hosts, but if it is on the same host as the agent relying on it for config, option 1 would be the best thing.

We do use the watch APIs for the various config sources when available, but it might be simple enough to just tweak the logic that starts the watch a bit since it should already handle the case where the service goes down after the first fetch of the remote config.  I'll take a look and see.

**Comment by keitwb** [comment]
I haven't forgotten about this.  I got it working for Consul but got stuck making the other config sources behave properly and then got pulled off on other things.  Will try and work out the other ones soon.

**Comment by jalaziz** [comment]
Thanks for the update!

We actually recently faced something similar with vault recently. Although, in the vault case, it was failing to connect simply from the remote source definition (probably because it's trying to authenticate on initialization?).

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
