### ISSUE TITLE
Docker memory stats are misleading

### ISSUE THREAD

**Issue by chrisgilbert** [signalfx/signalfx-agent#1009]
We've just switched to the smart agent, and had some problems with docker memory stats again, which we'd also had with the old collectd agent.

In the smart agent, you've correctly deducted cache when exposing `memory.percent`, in the enhanced statistics here:

https://github.com/signalfx/signalfx-agent/blob/b565dcda82c068defaf00939f9c0275e4ba4ce86/internal/monitors/docker/conversion.go#L160

However, you are not deducting it here:
https://github.com/signalfx/signalfx-agent/blob/b565dcda82c068defaf00939f9c0275e4ba4ce86/internal/monitors/docker/conversion.go#L151

I think this is incorrect, and gives a misleading figure which will cause people to think their app is using too much memory.

A lot of people will try to calculate percentage by doing `memory.usage.total / memory.usage.limit * 100`. This will then produce a completely incorrect value.

It's confused some of our developers, as they have seen very odd memory behaviour in applications. 

The reason for this being misleading, is that the buffer cache increases with I/O. As such, any application doing enough I/O will eventually appear to consume all the memory. Which of course is not is what is actually happening!

Here's an example of the problem which I produced with smart agent. To do it, I execed into a couple of containers and ran these commands, to create a 500MB and then a 1000MB file and delete them again.

It is then reflected as 500 and 1000MB more memory use in the stats.
```
dd if=/dev/zero of=test.dd bs=1M count=500
rm test.dd
```
And then on the other container:
```
dd if=/dev/zero of=test.dd bs=1M count=1000
rm test.dd
```
Here's the memory graph.

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/361112/66132287-b8fad680-e5ec-11e9-9ce4-6ac034ce293a.png">

As you can see, the memory use spikes to 100% and then back down when I delete the file. This shows that the stats are really not helpful once the container does any I/O.

If you compare stats with what comes from ECS in Amazon cloudwatch, the stats there are much more accurate, because they decided here to start deducting the buffer cache:

https://github.com/aws/amazon-ecs-agent/issues/280

I think the root problem is down to this decision by the docker API developers to expose memory usage, including buffer cache:

https://github.com/docker/libcontainer/pull/506

This was a questionable decision in my opinion, because developers consuming the API (like SignalFX) will trust the figure, and then expose it to end users. It causes much confusion, since it bears no real link to the memory use of the application inside the container.

I guess it's another one of those "naming is hard problems" since the devs who put cgroups into the Linux kernel probably made a bad choice of name in the first place too. `memory.usage_in_bytes` is deceptively simple, and doesn't tell you it actually includes page cache and kernel memory use too.

**Comment by keitwb** [comment]
Ok, I recall the PR you made at https://github.com/signalfx/docker-collectd-plugin/pull/35 about a similar issue.

It is inconsistent, but I basically agree with the rational that the Docker project maintainer used in including it: https://github.com/docker/libcontainer/pull/518#issue-32985796 -- it is actually being used by the kernel and accounted directly to that process by the kernel -- and you can subtract out the cache metric using SignalFlow if you don't want it included, or just use the metric `memory.percent` (that is the main reason that metric exists, since otherwise you could just calculate it using total and limit).  `memory.usage.total` certainly can be misleading if you don't realize it includes files in kernel memory that are attributed to the process automatically.  It would be similar to if your application were caching the read files in dynamically allocated heap memory directly from disk and freeing the heap space if memory usage passed a certain threshold.  Additionally, if you are fairly sure you won't benefit from caching the file's content in memory, you can open it in "direct" mode on Linux to bypass buffer caches.  

In general, with metrics like this that are a passthrough from some kernel subsystem (in this case cgroups and the `memory.usage_in_bytes` stat), our general principle is to make them as simple a passthrough as possible without modification, that way the confusion is minimized for people that do understand the underlying system.  I did make a change to clarify the `memory.usage.total` metric (https://github.com/signalfx/signalfx-agent/pull/1010).

Also, consider the container memory stats to be very "high level".  For tracking specific applications, I would recommend relying more on things like runtime memory stats (e.g. JVM heap stats if it is Java) instead of cgroup stats coming from Docker anyway.

**Comment by chrisgilbert** [comment]
I can see some argument including it, but not as the default memory use metric. I'd suggest `memory.stats.rss_total` is a much more useful one for most people to see, though there might be a better choice.

Speaking for our own use case - the main reason we monitor container memory use is to see if we have correctly sized our container memory constraints for the applications running in them.

The reason I'm pressing it is that I feel like it does a disservice to other developers if I don't. 

I am mainly just trying to save people some time and headaches, since I spent hours trying to work out why the Signal, ECS and Docker stats memory figures were so far apart.

I fear others will go searching for phantom memory leaks in their applications that don't exist. Which is something several of our developers have done too, after trusting these figures.

I honestly don't think there are too many people who understand the subtleties of the Linux buffer cache, unless they delve into the workings of the kernel. From a kernel developer's perspective, lumping all the buffer cache in with anonymous memory _might_ make sense. To everyone else, it's pretty irrelevant. Linux uses almost all free RAM for buffer cache by default, so all applications will have some cache which they use, and I can't see why you'd want that counted with each container. It's an OS level optimisation. One that Windows does too, but just doesn't expose in such an obvious way.

However, all that memory is evictable - if your application wants 48MB RAM, and there's 32MB available below the docker memory limit, it will evict 16MB from the buffer cache and grant you the anonymous memory you asked for. It doesn't throw an OOM exception.

> It would be similar to if your application were caching the read files in dynamically allocated heap memory directly from disk and freeing the heap space if memory usage passed a certain threshold.

Maybe, and you'd want to see that memory use in your container memory figure because you have control over it. You'd also want to see how the garbage collector is behaving, because that's a facet of the application you are monitoring.

You _wouldn't_ want to see the OS optimisation of free memory at the container level. If you want to see it at any level, it's at the host level. But actually, your agent shows used memory without buffers and cache at that OS level.

It looks like you use the gopsutil to get it for Linux servers, and that does precisely what I feel it should - it deducts them before supplying the Used figure.

https://github.com/shirou/gopsutil/blob/master/mem/mem_linux.go#L135

If it didn't do that, people would think their servers were about to start killing applications all the time, when of course, they are fine, and Linux is just using free RAM to optimise performance. 

This is our new config FWIW:
```
- type: docker-container-stats
  enableExtraCPUMetrics: true
  enableExtraMemoryMetrics: true
  datapointsToExclude:
  - metricNames:
    - "memory.stats.*"
    - "memory.usage.total"
    - "!memory.stats.total_rss"
    - "cpu.*"
    - "!cpu.percent"
    - "!cpu.usage.system"
    - "!cpu.usage.total"
```

Most of the time `memory.percent` is what we want, but it is also nice to be able to see garbage collection behaviour and so on, which we should be able to see from the RSS figure too.

**Comment by chrisgilbert** [comment]
Sorry for the long explanation. I think I was just a little confused about why the default memory stats include a figure most people won't understand, and that you have to enable all the extra memory stats to get the `memory.percent` one which is correctly calculated. 

Of course enabling that adds all the other `memory.stats` ones, of which there are a great number, and so it dramatically increases the DPM you'll be sending to signal. 

I think there's a good argument for including `memory.percent` as a default stat, since you can't calculate it correctly from the usage stats you are including by default.

**Comment by keitwb** [comment]
Ok, you've made a pretty good case and making the default metrics that we do send as usable as possible is important.

We are preparing for a 5.0 major release and so I'll exclude buffer cache totals from `memory.usage.total` in that release, since it will technically be a non-backwards compatible change (although I'm assuming nobody will have detectors for memory usage being unexpectedly _low_).

Also, if you are using the agent version >= 4.7.0 you can do this to enable specific non-default metrics:

```
- type: docker-container-stats
  extraMetrics:
   - memory.stats.total_rss
   - cpu.*
   - ....etc
```

Should be a lot more intuitive than using `datapointsToExclude` and the boolean flags on the monitor config.

**Comment by chrisgilbert** [comment]
Great, thanks for the tip, I didn't spot that option.

I hope it will save someone else a bit of head scratching in the future, thanks for listening!
