### ISSUE TITLE
Configuring Linux capabilities for collectd binary.

### ISSUE THREAD

**Issue by Meijuh** [signalfx/signalfx-agent#1251]
To make the collectd smart plugin work I need to set capabilities on the the collectd binary that ships with signalfx. This can be done by running the commandline `sudo setcap cap_sys_rawio=ep /usr/lib/signalfx-agent/bin/collectd`, or by configuring the signalfx systemd service similarly to the collectd service described at https://github.com/collectd/collectd/blob/master/contrib/systemd.collectd.service. Now, both methods won't be reliable when signalfx-agent is updated with (for instance) apt, since both the binary, as well as the systemd configuration file at `/lib/systemd/system/signalfx-agent.service` will be overwritten

A workaround is to run a cronjob every minute or so that sets the capabilities on the collectd binary, but I wonder if there is a better and more supported solution.

These linux capabilities are more described at http://man7.org/linux/man-pages/man7/capabilities.7.html; to read those S.M.A.R.T. attributes you will need the CAP_SYS_RAWIO capability.

There is also a way to do it with `pam_cap.so` module as described at http://blog.siphos.be/2013/05/restricting-and-granting-capabilities/, but I don't really trust the websites I found so far; I'd like to find to find a more trusted website that described how to resolve it user-based.

**Comment by keitwb** [comment]
Hi @Meijuh, you could try [overriding the systemd service file](https://askubuntu.com/a/659268) for the agent and using the [AmbientCapabilties](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Capabilities) option on the service file (as long as you are using a relatively recent version of systemd).  This method should protect your changes from apt upgrades.

 I think you still need to do the `setcap` on the `signalfx-agent` and/or `collectd` binary, but you should be able to do that in an `ExecStartPre` script run in the overridden systemd service file for the agent instead of a cron job.

Let me know if that helps.

**Comment by Meijuh** [comment]
Thank you! I also had to add `PermissionsStartOnly=true`, because the `signalfx-agent` user is not allowed to run `setcap` on the `collectd` binary. My overridden systemd service file is now as follows.

    [Service]
    PermissionsStartOnly=true
    AmbientCapabilities=CAP_SYS_RAWIO
    ExecStartPre=/sbin/setcap cap_sys_rawio=eip /usr/lib/signalfx-agent/bin/collectd

**Comment by keitwb** [comment]
Ok, great, thanks for sharing the override file.
