### ISSUE TITLE
Conflicting configuration keys

### ISSUE THREAD

**Issue by rcastley** [signalfx/signalfx-agent#1334]
In the Smart Agent config-schema there is no reference to `clusterName`

https://github.com/signalfx/signalfx-agent/blob/master/docs/config-schema.md

However, in the Helm docs it is reference along with the SmartGateway

https://github.com/signalfx/signalfx-agent/blob/fa5d3ec0d5030be36364d68a12f17bdca0fb7f5c/deployments/k8s/helm/signalfx-agent/values.yaml#L134

https://github.com/signalfx/signalfx-agent/blob/fa5d3ec0d5030be36364d68a12f17bdca0fb7f5c/deployments/k8s/helm/signalfx-agent/values.yaml#L15

As `clusterName` no longer exists in the `config-schema` is this key valid anymore?

**Comment by mstumpfx** [comment]
@rcastley I don't think there was ever a `clusterName` config option in the agent. The `values` uses this as a helper to provide values to the `cluster` config option in agent [0], as well as setting the `kubernetes_cluster` global dimension [1].

0. https://github.com/signalfx/signalfx-agent/blob/fa5d3ec0d5030be36364d68a12f17bdca0fb7f5c/deployments/k8s/helm/signalfx-agent/templates/configmap.yaml#L41
1. https://github.com/signalfx/signalfx-agent/blob/fa5d3ec0d5030be36364d68a12f17bdca0fb7f5c/deployments/k8s/helm/signalfx-agent/templates/configmap.yaml#L53

**Comment by rcastley** [comment]
@mstumpfx Thank you .. but I am referring to Helm charts ... that template refers to `clusterName`

**Comment by rcastley** [comment]
OK, ignore me ... the naming convention is confusing me ... sorry!

**Comment by mstumpfx** [comment]
@rcastley it is slightly confusing because it's not a 1:1 correspondence from the helm config to agent config - this `clusterName` is just a convenience option.

If you check out our supplied configmap you'll see it does the same thing:

https://github.com/signalfx/signalfx-agent/blob/v5.0.0/deployments/k8s/configmap.yaml#L22
https://github.com/signalfx/signalfx-agent/blob/v5.0.0/deployments/k8s/configmap.yaml#L29
