### ISSUE TITLE
mssql monitor doesn't implement includeQueries

### ISSUE THREAD

**Issue by cdhunt** [signalfx/signalfx-agent#1394]
I don't understand why the telegraf monitor provides two different query lists, but QueryVersion 2 doesn't include the DatabaseSize queries which I want. Implementing the IncludeQueries parameter would allow me to customize the executed queries to better suit our needs utilizing the well defined existing query library included in the monitor.

- [Upstream telegraf input](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sqlserver/sqlserver.go#L19).

**Comment by keitwb** [comment]
What I would recommend for now is to create two monitor configs of `telegraf/sqlserver`, one with `queryVersion: 2` and then another with `queryVersion: 1` along with `excludedQueries: [PerformanceCounters, WaitStatsCategorized, DatabaseIO, ServerProperties, MemoryClerk]` and whatever other v1 queries you don't want.  That should get you what you want.

If I'm reading the upstream sqlserver plugin code correctly, using IncludeQueries with QueryVersion: 2 won't get you the DatabaseSize query because it isn't defined at all in version 2, so IncludeQueries won't help you.  The version of telegraf we use in the Smart Agent right now doesn't have that option anyway.

Let me know if that works.

**Comment by cdhunt** [comment]
Yeah. Looking further into it and I don't see what IncludeQuery is even supposed to do. I also see an issue where the DatabaseSize queries don't report data to SignalFx. I have a case open with support for that. I never thought about running the same monitor with different parameter - Thanks!
