### ISSUE TITLE
Varnish integration does not work

### ISSUE THREAD

**Issue by xp-1000** [signalfx/signalfx-agent#1399]
Hello,

I try to setup varnish integration https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.varnish.html without success, I always got ther following error:

```
Jul 27 08:33:43 ip-10-10-30-14 signalfx-agent[22451]: time="2020-07-27T08:33:43Z" level=error msg="varnish plugin: Unable to open connection." collectdInstance=monitor-10
Jul 27 08:33:43 ip-10-10-30-14 signalfx-agent[22451]: time="2020-07-27T08:33:43Z" level=info msg="read-function of plugin `varnish/localhost' failed. Will suspend it for 20.000 seconds." collectdInstance=monitor-10
```

I tried to use a custom collectd template:

```
  - type: collectd/custom
    template: |
     LoadPlugin varnish
     <Plugin "varnish">
       <Instance>
         CollectCache       true
         CollectConnections true
         CollectBackend     true
         CollectSHM         true
         CollectESI         true
         CollectFetch       true
         CollectHCB         true
         CollectSMA         true
         CollectSMS         true
         CollectTotals      true
         CollectWorkers     true
         CollectUptime      true
         CollectVCL         true
         CollectStruct      true
         CollectObjects     true
         CollectSession     true
         CollectVSM         true
       </Instance>
     </Plugin>
```

I tested varnish5 and varnish6 on debian: same result

I tested add `-n toto` to `varnishd` process and change `<Instance toto>` on collectd conf : same result.

Someone could help me?

**Comment by keitwb** [comment]
Quite possibly it is because we link against libvarnish 4.x due to some issues we had with linking collectd with the newer varnish libraries a while back.  For that reason, we never made it a "first-class" fully-supported monitor in the agent.

It looks like Varnish 5+ has a JSON output for the varnishstats cli tool.  You could use the [python-monitor](https://github.com/signalfx/signalfx-agent/blob/master/docs/monitors/python-monitor.md) monitor to write a little python script to scrape the JSON output of a subprocess call to varnishstats and convert them to metrics and do it exactly how you want.  That seems to be what other agents do.  I think the actual metrics come from a shared memory segment on the Varnish process, so it's going to be pretty tough to access except through either libvarnish C library or varnishstats cli tool.

**Comment by xp-1000** [comment]
I think https://github.com/signalfx/signalfx-agent/pull/1446 should resolve this issue
