### ISSUE TITLE
Issue with jetty stats mBean for GenericJmx plugin 

### ISSUE THREAD

**Issue by apoorva88** [signalfx/signalfx-agent#1450]
With collectd we had a Mbean "Jetty" with objectName org.eclipse.jetty.server.handle, but same configuration in Smart Agent results in below error:
warning msg="No MBean matched the ObjectName org.eclipse.jetty.server.handler:type=statisticshandler,id=0" collectdInstance=global plugin=GenericJMXConfMBean

Collectd configuration:
 <MBean "jetty">
     ObjectName "org.eclipse.jetty.server.handler:type=statisticshandler,id=0"
     InstancePrefix "jetty"
     <Value>
       Type "response_time"
       Table false
       Attribute "requestTimeMax"
       InstancePrefix "requestTimeMax"
     </Value>
[jmx.txt](https://github.com/signalfx/signalfx-agent/files/5172029/jmx.txt)

**Comment by keitwb** [comment]
Hi @apoorva88, there is no real difference between the collectd GenericJMX and the same one in the Smart Agent.  The Smart Agent is just running collectd with the config that you provide.

Most likely there just isn't that MBean.  I would recommend using the [`jmx` monitor](https://github.com/signalfx/signalfx-agent/blob/master/docs/monitors/jmx.md) instead of GenericJMX as `jmx` is far more powerful and you can even use print statements to debug what mbeans are there and their attributes.

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
