### ISSUE TITLE
Equivalent metrics from cadvisor

### ISSUE THREAD

**Issue by xp-1000** [signalfx/signalfx-agent#1473]
Hello,

I seen the very interesting doc https://github.com/signalfx/signalfx-agent/blob/master/docs/faq.md#how-do-i-monitor-cpu-usage-for-kubernetes-pods-that-have-cpu-limits

I would ask if there is an equivalent of the formula provided to monitor case 1 using cadvisor metrics :

`(container_cpu_usage_seconds_total/10000000)/(container_spec_cpu_quota/container_spec_cpu_period)`

but with https://docs.signalfx.com/en/latest/integrations/agent/monitors/kubelet-metrics.html or https://docs.signalfx.com/en/latest/integrations/agent/monitors/kubernetes-cluster.html metrics ?

Thanks for the help

**Comment by keitwb** [comment]
There is, assuming you use `resource.limits` on your K8s pods.  The metrics `container_cpu_utilization / kubernetes.container_cpu_limit` will give you the percentage of the limit used (0-100).  The `container_cpu_utilization` metric has units of % of 1 CPU core used (so its range is [0, 100*num_cores]), and the `kubernetes.container_cpu_limit` has units of cores (so its range is [0, num_cores]).  In theory it should give you the same output as the original formula in the FAQ since limits get directly translated into cpu quota/period when the container is run (at least that is how it was implemented when I wrote that FAQ a few years ago).

I'll update the FAQ to clarify it using the new metrics.

**Comment by xp-1000** [comment]
OK it was what I thought but there was a missing piece:

> In theory it should give you the same output as the original formula in the FAQ since limits get directly translated into cpu quota/period when the container is run (at least that is how it was implemented when I wrote that FAQ a few years ago).

Thanks for the help
