### ISSUE TITLE
update telegraf dependency

### ISSUE THREAD

**Issue by xp-1000** [signalfx/signalfx-agent#1512]
Hello,

is this possible to sync https://github.com/signalfx/telegraf with upstream and update go mod dependency here ?

The signalfx version of telegraf is old and I would like to use metrics which are not available.

thanks

**Comment by xp-1000** [comment]
I tried to use last telegraf version here https://github.com/xp-1000/telegraf/tree/v1.16.1.sfx0 but I got this error when I try to build the agent:

```bash
$ make signalfx-agent 
go generate ./...
# github.com/hashicorp/go-gcp-common/gcputil
/go/pkg/mod/github.com/hashicorp/go-gcp-common@v0.0.0-20180425173946-763e39302965/gcputil/credentials.go:155:27: oauth2Client.GetCertForOpenIdConnect undefined (type *"google.golang.org/api/oauth2/v2".Service has no field or method GetCertForOpenIdConnect)
pkg/monitors/zcodegen/codegen.go:8: running "sh": exit status 2
Makefile:61: recipe for target 'signalfx-agent' failed
make: *** [signalfx-agent] Error 1
```

**Comment by keitwb** [comment]
Unfortunately we tried to upgrade Telegraf to latest a while back and it broke metric backwards compatibility due to some  major changes they made to metrics.  So if we did upgrade telegraf we would have to rerelease the agent with a major version increment.  

We've been trying to get a SignalFx output into the upstream for a while now (https://github.com/influxdata/telegraf/pull/6714) but they are asking for major changes to it to avoid bringing in so many deps.  I would recommend cherry-picking that commit in that PR onto the tag  of whatever telegraf version you want to use and it should work fine.  You don't really need anything from our fork if you are also using the Smart Agent.

**Comment by xp-1000** [comment]
> We've been trying to get a SignalFx output into the upstream for a while now (influxdata/telegraf#6714) but they are asking for major changes to it to avoid bringing in so many deps. I would recommend cherry-picking that commit in that PR onto the tag of whatever telegraf version you want to use and it should work fine. You don't really need anything from our fork if you are also using the Smart Agent.

I already subscribed to this PR and hope you will be merged. support signalfx as output for telegraf upstream agent would represent a good addition.

So what you propose is :
- I fork https://github.com/signalfx/telegraf/
- I cherry pick what I need from upstream https://github.com/influxdata/telegraf
- create a PR
- when merged the changes on plugins will be available from smart agent

is it correct?

**Comment by keitwb** [comment]
No, fork telegraf upstream to whatever version best suits you.  Then apply that patch and build.  That will give you the most "pure" Telegraf available with only our output added.

**Comment by keitwb** [comment]
Yes, hopefully we can get the PR merged soon.

**Comment by xp-1000** [comment]
> No, fork telegraf upstream to whatever version best suits you. Then apply that patch and build. That will give you the most "pure" Telegraf available with only our output added.

Either I do not understand something or I did not explained properly my need.

So let me take an example, adding telegraf based monitor into signalfx agent for mongo:

https://github.com/signalfx/signalfx-agent/compare/master...xp-1000:telegraf_mongo

On signalfx telegraf fork the cluster stats are not available:
https://github.com/signalfx/telegraf/blob/master/plugins/inputs/mongodb/mongodb.go#L20

because added in newer version in telegraf upstream:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/mongodb/mongodb.go#L19

so in my understanding, if I want enjoy some "recent" features or bugfixes from telegraf into the signalfx agent we need to upgrade your telegraf fork (entirely or partially via cherry pick), tag a new version and bump the dependency in https://github.com/signalfx/signalfx-agent/blob/master/go.mod#L9 

I think what you propose is to build the upstream telegraf version applying your PR (not merged yet) to use telegraf instead of signalfx agent (but this is not what I want even if could be probably useful in some cases)

**Comment by keitwb** [comment]
We originally just included some Telegraf plugins to get some quick Windows compatibility but not really as some general mechanism to pull in Telegraf plugins whenever convenient.  Updating Telegraf in the agent would mean majorly breaking backwards compatibility since Telegraf has updated their metrics in backwards incompatible ways (we attempted to upgrade it several months ago and ran into this in a major way).  Since the whole Telegraf project is one Go module, you have to pull in the same version of telegraf for all packages in it, so there is no way to piecemeal it.

Also the branch that the agent uses is not `master`, but https://github.com/signalfx/telegraf/tree/signalfx-agent.  This still doesn't have the new mongo stuff though.

For maximum flexibility, if you really need a telegraf plugin, we recommend just running telegraf and pointing the output to the local SignalFx agent and getting all of the host dimensions automatically.  Otherwise we would much rather just update the collectd/mongo monitor or make a new one in Go natively.

In retrospect I probably wouldn't have even allowed any telegraf plugins to be brought in but at least now I can stop any new ones from being added.  I hope you understand.  That does not mean, however, that the telegraf code cannot be used as a basis for a native Smart Agent monitor, as long as proper legal attribution is given in the source.

**Comment by xp-1000** [comment]
I understand what you say. If it is not attended to be a general mechanism to extend the signalfx agent, so this issue does not make sens.

However, I would like to share you my humble opinion (which is obviously influenced by the MSP perspective).

Provide embedded and native "collectors" ready to use is one of the biggest challenge and added value of a next generation monitoring tool. It is lot of work it is true but it allows user to do not think about metrics collection and focus on the rest, it is work out the box. Crawler integrations are crucial but the agent is also important.

I think this is even truer for a saas and commercial product, for example, datadog provides a huge base of plugins to support lot of existing and popular tools. 
Nevertheless, I think we should not focus too much on quantity and do not forget quality. 

This is why, when I discovered signalfx, I liked the approach to reuse existing robust monitoring agent like collectd and telegraf to not have to reinvent the wheel (sometimes less good) and capitalize on community work. 

Anyway, this is probably the direction this world will take with https://github.com/open-telemetry/opentelemetry-collector-contrib but for now, signalfx agent, as good as it is, heavily lack of monitors to cover common community needs, you say it:

> We originally just included some Telegraf plugins to get some quick Windows compatibility but not really as some general mechanism to pull in Telegraf plugins whenever convenient

I did not use windows from years now and I am probably not his best defender, however, a product of the class of signalfx should fully support this platform which is not anecdotal so you filled the gaps thanks to telegraf.
This is exactly the same goal of this issue: find the best way to provide to signalfx the agent collection capabilities it deserves.

With collectd deprecated and now telegraf "stucked" it does not remain lot of "future proof" monitors in the agent and if we need to rewrite every collectd/telegraf based monitors into "pure go" into the agent everytime they are not enough (because obsolete) we loose the advantage of I spoke before.

Using the upstream telegraf agent is not a solution but a workaround to signalfx agent lacks. Running 2 different monitoring agents is the same instance is not desirable especially while singalfx output is not in the official binary.

Don't take this bad please I am just a little disappointed because I think telegraf provides a good and large list of plugins and reuse them in signalfx agent is an efficient and smart way to extend it.

Feel free to close this issue, may be I don't like the answer but it is perfectly relevant for the question.

**Comment by keitwb** [comment]
Yes, the OpenTelemetry collector is intended to be an vendor-neutral agent where everybody can contribute and the goal is to have much more integration support than the Smart Agent.  We also considered doing the "embedded telegraf" approach there but decided against it since it makes it harder to support and modify since it is a third-party repo.

Another thing I would suggest to you, if you have not already considered it, is [prometheus exporters](https://prometheus.io/docs/instrumenting/exporters/).  The `prometheus-exporter` monitor fully supports all of these, and there are a ton of them.  The downside to them is that you have to run a separate app alongside the thing being monitored, usually in some kind of side-car setup, but for all the ones I have dealt with they are pretty easy to deploy.  However, more and more services are getting Prometheus exporters built-in (e.g. Redis, RabbitMQ) so hopefully that trend continues.  The exporters also have the advantage of being independently upgradable, something that isn't really feasible with a centralized agent.

I'll leave this open for now as we get a lot of questions about telegraf so this will probably be revisited soon.

**Comment by xp-1000** [comment]
thanks for the answer. 

Yes I already use prometheus exporters for some needs like cloudera and alibaba monitoring.
As you said it add dependency to a new app to deploy and this is totally acceptable for this "specific" usage.
I would prefer to not depend on this for common usage vastly deployed.

About opentelemetry collector, do you recommend to make PR for new "monitor" as "receiver" into collector contrib instead of signalfx smart agent in future ?

I know I can forward smart agent metrics to opentelemetry collector which will send to signalfx. If I need to install and run a second app to add missing signalfx metrics I would prefer to use opentelemetry collector instead of telegraf.
But I am not sure of every implications especially if opentelemetry collector will set host metatada like smart agent does.

Notice, I know this collector is beta and do not have many receivers for now but if I need to add some (not available in smart agent too) I suppose it is similar so I take your advice.

**Comment by keitwb** [comment]
Running Smart Agent and the Otel collector side-by-side would work, and is more or less our transition plan for people in the near term.  So if you do contribute a receiver to the Otel Collector, you will be better off long-term since we will eventually put a hard stop on all new features in the Smart Agent (not yet though).  You also have the opportunity to mold the receiver to your preference, similar to how you did with the `http` monitor here.

The collector is written with resource usage in mind so the cpu/memory overhead should be fairly minimal to run both.  Only the management/deployment of them both will be the downside.

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
