### ISSUE TITLE
Error shipping datapoints to SignalFx

### ISSUE THREAD

**Issue by puremjlee** [signalfx/signalfx-agent#1569]
Hi All, I am new to SignalFx. I am running kubernetes and deploy smart-agent with helm chart. The agent container is lunched but the log says

time="2021-01-09T12:02:01Z" level=error msg="Error shipping datapoints to SignalFx" error="failed to send/receive http request: Post \"https://ingest.us0.signalfx.com/v2/datapoint\": dial tcp: i/o timeout: map[Connection:[keep-alive] Content-Type:[application/x-protobuf] User-Agent:[golib-sfxclient/1.0 (gover go1.14.2)] X-Sf-Token:[xxxxxxxxxxxxxxx]]"

The token and realm info are correct. What should I do?

**Comment by keitwb** [comment]
Hi @puremjlee this looks like a network issue on your side.  Does your Kubernetes cluster allow outbound traffic from the agent pod?  Check what firewalls might be in place.  [This guide](https://docs.signalfx.com/en/latest/admin-guide/allow-services.html) might be helpful.

**Comment by RPooja08** [comment]
I am also facing the same issue on simple windows server.

**Comment by keitwb** [comment]
@dloucasfx have you seen anything like  this before with Windows?  I suspect it is a firewall or network issue in the environment.

**Comment by dloucasfx** [comment]
Do we always fail to deliver datapoints or it is happening sporadically?
- If we're always failing, then @keitwb is correct, this will most likely be a firewall/network issue. One way to validate is to curl our ingest endpoint manually from the same host/container where the agent is running and try to emit some datapoints.
If you don't have curl on windows, this can be done
```
$json = @{
     gauge = @(
     	@{
     		metric = "memory.free"
     		dimensions = @{
     			host = "server1"
     		}
     		value = "42"
     	}
     )
 } | ConvertTo-Json  -Depth 3

$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"

$headers.Add("X-SF-TOKEN", 'replace_with_actual_token')

$response = Invoke-RestMethod 'https://ingest.<replace_with_realm>.signalfx.com/v2/datapoint' -Method Post -Body $json -ContentType 'application/json' -Headers $headers
```

You might need to run this first
```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

- If the issue is sporadic, then it's most likely impacted by windows network stack performance or/and overall performance of the windows host.
If this is the case, then you need to check if the windows host is under stress; A bandaid is to increase the timeout which is now configurable https://github.com/signalfx/signalfx-agent/pull/1507

**Comment by puremjlee** [comment]
Hi everyone, 

I resolved this issue with the link : https://revolgy.com/blog/revolgy-signalfx-all-you-need-to-know-before-deploying-a-managed-monitoring-solution/

Deploy with Helm didn't work. The only way to deploy agent under kubernetes is referring the link above. The manual should be modified. 

Hope this help for someone who has same issue with me.

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
