### ISSUE TITLE
how to run a powershell script from exec plugin

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1921]
We have the powershell 7 version and trying to run the powershell script via exec plugin. but getting error.

![image](https://user-images.githubusercontent.com/68017992/134326273-c9c9f966-8a92-44c0-a97b-87d8a2414c4c.png)

We have done the below configurations in yaml file.

Config:

![image](https://user-images.githubusercontent.com/68017992/134326355-52a44d88-58e7-4735-92f9-240f9319b10a.png)

**Comment by vairolett0** [comment]
i run them like this

- type: telegraf/exec
  command: powershell.exe "C:\ProgramData\SignalFxAgent\monitors\ps-script.ps1"
  intervalSeconds: 60
  telegrafParser:
    dataFormat: influx


sometimes script dont work as expected on powershell, probably due to their runtime, which is why i have a 1 minute interval.

I've had better luck with JSON format outputs than with influx outputs

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
