### ISSUE TITLE
Questions about python monitor

### ISSUE THREAD

**Issue by rklabs** [signalfx/signalfx-agent#744]
Hello,

I had a couple of questions about python monitor in signalfx. 

1. `pip` is not installed as part of python dist which is installed along with `signalfx-agent` which is understandable since installing new packages or upgrading existing packages may have unintended side effects. I wanted to understand the motivation for not including `pip`. `pip` would actually help us in installing packages which are required for our custom checks.

2. Why are the modules in https://github.com/signalfx/signalfx-agent/tree/v4.6.0/python not packaged and published to pypi? We could build python wheel and distribute via private artifactory or clone the repo and add the package to `sys.path` but that is an ugly hack. If we could install signalfx packages mentioned above via `pip` that would be ideal.

Thanks,
Raju Kadam

**Comment by keitwb** [comment]
Hi @rklabs,

1. The `pip` binary isn't there but the pip module is there.  You can run `PYTHONHOME=/ python -m pip` in the Docker image _OR_ `PYTHONHOME=/usr/lib/signalfx-agent python -m pip` if running it straight from the deb/rpm package installation.  The main limitation of doing pip installs is that any installs that require C-extension compilation probably won't work, but that is mitigated by the prevalence of wheels.  

If you have dependencies that require extension compilation or you want to use a specific version of Python, you can install Python separately on your host and use the `pythonBinary` config option to the [python-monitor](https://github.com/signalfx/signalfx-agent/blob/v4.6.0/docs/monitors/python-monitor.md) (if you are installing the agent on a host and not running the container image).  There is no such config for the `collectd/python` monitor because Python is linked directly in the collectd binary but you should really consider using the `python-monitor` monitor to extend the agent anyway since it is much more natural to our datapoint format.

2. We can definitely publish that as a package to Pypi if it makes things easier for you.  I'm assuming the main reason you want it there is for development/IDE support?  Or is it something else?

Let me know any other feedback/issues on the Python stuff -- this is still pretty new so it has a lot of room for maturation.

**Comment by rklabs** [comment]
Thanks for the quick reply!

1. Thanks for the tip! I was looking for `pip` executable in `bin` directory of `signalfx-agent` installation. But this works as well and currently, we don't really need C-extension for python.

2. Thanks for quickly creating the [pr](https://github.com/signalfx/signalfx-agent/tree/v4.6.0/python) to install signalfx modules required for python monitor. We are currently migrating a bunch of custom metric collection scripts and we wanted to create a virtual environment with dependencies including from signalfx and use the python interpreter installed in a virtual environment rather than use the one packaged along with signalfx-agent. We want to maintain a clear boundary for the custom scripts and not mess with the python dist provided by signalfx-agent.

Yeah! sure thing, we have just started using signalfx and it's been a fun ride and if there is anything I will reach out to you.

**Comment by keitwb** [comment]
Ok, I released it on Pypi: https://pypi.org/project/sfxpython/.  Let me know if you have any more issues/questions.

**Comment by rklabs** [comment]
🎊 Thank you!
