### ISSUE TITLE
host_mem_total metadata is reported as a string value

### ISSUE THREAD

**Issue by cdhunt** [signalfx/signalfx-agent#985]
I would like to be able to filter on a range of values on `host_mem_total` host metadata property but it is being reported as a string so the range operation doesn't work. Can this be recorded as an `int`?

**Comment by keitwb** [comment]
Hi @cdhunt.  This is a property on the `host` dimension, and properties are string key/value pairs, no ints allowed.

You can get somewhat close to the total value with `C` in the following SignalFlow program:

```
A = data('memory.used').sum(by=['host']).publish(label='A', enable=False)
B = data('memory.utilization').scale(0.01).sum(by=['host']).publish(label='B', enable=False)
C = (A/B).publish(label='C')
```

This isn't exact due to the rounding error.

The best thing for us to do is to just add a `memory.total` metric to the `memory` monitor if you have a good use case for it.  Can you explain more about what you are trying to do with a range operation?

**Comment by cdhunt** [comment]
I don't need the value a metric. I need to filter by the value because we configure detectors differently for high-memory systems.

**Comment by jaysfx** [comment]
@cdhunt In order to get you the best possible solution please open a support ticket from within the app. Thanks!
